# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='RankItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('score_sum', models.CharField(blank=True, max_length=16)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=16)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Problem')),
                ('rank_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.RankItem')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='oj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.OJ'),
        ),
        migrations.AddField(
            model_name='alias',
            name='oj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.OJ'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreitem',
            unique_together=set([('rank_item', 'problem')]),
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together=set([('oj', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('name', 'oj')]),
        ),
    ]
